### ISSUE TITLE
Have you checked out the (ex-85 MB) Lambda layer?

### ISSUE THREAD

**Issue by MichaelPeter** [aletc1/examples-convert-pdf-azure-functions#1]
https://github.com/shelfio/libreoffice-lambda-layer

Hi, I really like this sample, I came here since i got inspired by the 85 MB AWS Lambda and wanted something simular for azure.
I am still figuring it out but shouldn't it be possible to use the same binaries on azure?

Just build your project and the Docker image is 1,5 GB, thats a bit large

**Comment by aletc1** [comment]
Hi @MichaelPeter,

Yes, it should be possible. There are techniques to shrink up to 70% dotnet containers (see more here https://itnext.io/smaller-docker-images-for-asp-net-core-apps-bee4a8fd1277) so you may clone and try to improve the process even do a PR if you like. 

My goal was just to showcase the possibility, the code is not production ready, but I do not see any problem in using a smaller LibreOffice binary (like in the AWS Lambda project) and then reducing the Azure Function code using the mentioned techniques (maybe using also alpine distribution to shrink it further).

**Comment by MichaelPeter** [comment]
Thank you very muchfor the reply,

regarding alpine images I already checked since libreoffice also provides alpine images. 

But here I still lack azure knowlege, since the azure functions image is debian based? and other base images are then not supported for the consumption plan? 

Also I guess the azure function docker layer is in the azure evironment locally cached and in an azure environment faster (loaded) ?

**Comment by aletc1** [comment]
I am afraid that you cannot use alpine in v3 functions:

> Using alpine would only reduce about 60 MBs from the OS base. However the functions runtime isn't compatible with musl-libc, so there are no plans to support alpine for v3 currently.
https://github.com/Azure/azure-functions-docker/issues/271

However, It is possible with v2 but Microsoft recommends using v3 because by the end of the year, they will change things in Azure that might break v2 functions. The current Azure Function docker runtime is big compared to others.

An alternative would be to go "Cloud native" and use Kubernetes (even in Azure with Azure Kubernetes Services) in which you can have a Virtual Node (pays only what you use) to run your custom alpine functions. Then you can use whatever cloud native framework you want (OpenFaaS, faasd, Knative, etc) and use KEDA to scale-to-zero.

**Comment by MichaelPeter** [comment]
Thanks for the infos, really helps me forward!
